Joost
INF1A-Team-2/Mini-Project-RPG-Game pull request #16
Opened 2023-02-13 14:41 UTC by Joost-Reintjes

2023-02-13 14:45 UTC, PieterLandaal approved these changes
Goed

2023-02-13 14:45 UTC, ZoutigeWolf requested changes
Je kan in de constructor de value1 en value2 beter minimumDamage en maximumDamage noemen.

2023-02-14 14:56 UTC, itsmorbintime123 approved these changes
Goed.

2023-02-15 12:50 UTC, MrBeast69420 approved these changes

2023-02-15 14:08 UTC, MrBeast69420 approved these changes

2023-02-15 14:12 UTC, ZoutigeWolf approved these changes
duimpie

2023-02-15 14:12 UTC, merged