Pieter
INF1A-Team-2/Mini-Project-RPG-Game pull request #17
Opened 2023-02-13 14:44 UTC by PieterLandaal

2023-02-13 14:46 UTC, ZoutigeWolf requested changes
de Id field in Location moet ID zijn, met hoofdletters.

2023-02-15 14:08 UTC, ZoutigeWolf approved these changes
dumpy

2023-02-15 14:09 UTC, itsmorbintime123 approved these changes

2023-02-15 14:09 UTC, MrBeast69420 approved these changes
LGTM

2023-02-15 14:10 UTC, merged