Mirzad
INF1A-Team-2/Mini-Project-RPG-Game pull request #18
Opened 2023-02-14 14:38 UTC by itsmorbintime123

moved declarations upwards out of class constructor and added constructor code

2023-02-14 15:11 UTC, ZoutigeWolf requested changes
De contructor komt niet overeen met de implementatie in World.cs
World geeft  na de id en de names 5 integers mee terwijl het er maar 4 kunnen  zijn volgens de class diagram. Moeten we morgen ff naar kijken

2023-02-14 15:28 UTC, itsmorbintime123 commented
World.cs heeft ook errors bij de op één na laatste integer van Monster. Dit is die error: Argument 7: cannot convert from 'int' to 'Loot'.

2023-02-14 15:30 UTC, ZoutigeWolf commented
Ja de loot list moet gwn altijd een new CountedItemList() zijn maar dan is er een parameter te weinig in de constructor

2023-02-14 15:31 UTC, itsmorbintime123 commented
Wat moet er dan precies verandert worden?

2023-02-14 15:32 UTC, ZoutigeWolf commented
World geeft 5 integers terwijl er maar 4 staan aangegeven in de class diagram dus we moeten morgen ff vragen hoe het zit

2023-02-14 15:35 UTC, itsmorbintime123 commented
Oké.

2023-02-15 14:16 UTC, Joost-Reintjes approved these changes

2023-02-15 14:16 UTC, ZoutigeWolf requested changes
L

2023-02-15 14:24 UTC, merged