Dev
INF1A-Team-2/Mini-Project-RPG-Game pull request #48
Opened 2023-02-21 15:30 UTC by itsmorbintime123

2023-02-21 15:33 UTC, PieterLandaal requested changes
In ieder geval bij snakes word de HP van de enemy niet opnieuw naar 7 gezet als je nog een keer gaat vechten, hierdoor win je instantly elk gevecht na de eerste

Ook het bericht "it dropped fang" moet "It dropped fang" zijn met hoofdletter

2023-02-22 10:21 UTC, PieterLandaal approved these changes

2023-02-22 10:22 UTC, MrBeast69420 approved these changes
lgtm

2023-02-22 10:24 UTC, Joost-Reintjes approved these changes

2023-02-22 11:59 UTC, ZoutigeWolf approved these changes

2023-02-22 12:00 UTC, merged